# Generated by Django 2.0.2 on 2018-12-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20181217_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
